include:
  - project: "platform/pipelines-templates"
    file: "/build/node/template-library-node-npm.yml"
    ref: "master"
  - project: "platform/pipelines-templates"
    file: "/build/node/template-library-node-npm-test-latest.yml"
    ref: "master"

default:
  image: node:16.15.0-alpine

stages:
  - prepare
  - test
  - package

publish:
  stage: package

  rules:
    - if: $CI_COMMIT_TAG

  before_script:
    - npm ci
    - npm run build

  script:
    - echo "${PRIVATE_NPM_REGISTRY_TOKEN}" > ${HOME}/.npmrc
    - npm publish
